# Generated by Django 4.2.1 on 2023-05-21 16:15

import core.recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.recipe.models.recipe_image_file_path),
        ),
    ]
